version: "3.9"

services:
  game:
    image: noughts-and-crosses
    container_name: noughts-and-crosses
    build:
      context: .
      target: development
    ports:
      - "8001:8001"
    networks:
      services-network:
        aliases:
          - app
    volumes:
      - ./game:/core/game
      - game_postgres:/vol/postgres
    depends_on:
      - game_db
    stdin_open: true
    tty: true
#    command: gunicorn --bind 0.0.0.0:8001 --log-level info --reload app:app


  game_db:
    image: postgres:alpine
    container_name: postgres_game
    environment:
      - DB_HOST=${DB__HOST}
      - POSTGRES_DB=${DB__NAME}
      - POSTGRES_USER=${DB__USERNAME}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
    ports:
      - "${DB__PORT}:5432/tcp"
    restart: always
    networks:
      services-network:
        aliases:
          - postgres
    volumes:
      - .:/core/game
      - postgres:/vol/postgres

  game_pgadmin:
    container_name: pgadmin_game
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - game_db
    networks:
      services-network:
        aliases:
          - pgadmin

volumes:
  postgres:
  game_postgres:
    name: game_postgres

networks:
   services-network:
     name: services-network
     driver: bridge
